import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/Theme-provider";
import { ClerkProvider } from "@clerk/nextjs";


const poppins = Poppins({
  weight: ["400", "500","600","700"],
  variable: "--font-poppins",
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${poppins.variable} `} suppressHydrationWarning>
        <body
          className={`antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
